documents = {
    'Учебные материалы': ['BQACAgIAAxkBAAIC4WJ-fSJ2fIh0A5s1LfwEdRX6KpyUAAJqHAACA9LwS7QW15BSqOqhJAQ', 'BQACAgIAAxkBAAIC4mJ-fSL9AtFQXMnS_OOgwT0vYMQoAAJrHAACA9LwS-7WHcbs6iltJAQ', 'BQACAgIAAxkBAAIC52J-fSYwTN8TXhSjd5ZfM3hrPlOvAAJsHAACA9LwS9UM4LjgKXUEJAQ', 'BQACAgIAAxkBAAIC6mJ-fSknEfKUHtpdiuBrWErXdI-5AAJtHAACA9LwS17eiZDrXt1xJAQ', 'BQACAgIAAxkBAAIC7WJ-fT6bppj9gQPLOy4JZTVVcFq1AAJxHAACA9LwS8huc7kzjYY3JAQ', 'BQACAgIAAxkBAAIC8GJ-fTwhl_KPeWPQMWX_uRpqULumAAJyHAACA9LwSx-ryffjLwyOJAQ', 'BQACAgIAAxkBAAIC8mJ-fT-k8b5hhEY8MawzpA4HC-B_AAJzHAACA9LwS5OUqBH-rtSNJAQ', 'BQACAgIAAxkBAAIC9GJ-fT-jhGqLFozsnzKZ3APbjWIqAAJ0HAACA9LwS8iy3Y3kulB4JAQ', 'BQACAgIAAxkBAAIC9WJ-fT8yg__WQiU1KpMyl33sOvALAAJ1HAACA9LwSxkqvsh0wOYsJAQ'],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
    '': [''],
}
youtube = {
    'Общее делание': ['https://youtu.be/00QDRYeBWlQ', 'https://youtu.be/vkcHC99Kwpg', 'https://youtu.be/XZJBjVSCTS8'],
    'Спорт': ['https://youtu.be/Bkrwk_JbLNg', 'https://youtu.be/9IhImEomIPQ', 'https://youtu.be/Gb0e0LiVrko', 'https://youtu.be/EaJTWWZhuNE', 'https://youtu.be/TDrfY6GFxLY', 'https://youtu.be/J0pivZzZTxQ'],
    'Детские праздники': ['https://youtu.be/iFVdaJRAT9U', 'https://youtu.be/TM-lGzzaRi8', 'https://youtu.be/33nKZvL22v4'],
    'Корпоративы': ['https://youtu.be/HroNwRf2CEg', 'https://youtu.be/22KfQurq4GQ', 'https://youtu.be/h-EGaLx-emM', 'https://youtu.be/hmU7bi9uf7g'],
    'Всероссийские форумы': ['https://youtu.be/QiCemPAnL44', 'https://youtu.be/RfTY-8tbFVk', 'https://youtu.be/pAyb-Yl9f-U', 'https://youtu.be/7dwVuaaMq1Y'],
    'Риэлторский юмор': ['https://youtu.be/i5rGeFo0YIQ'],
    'Семинары для населения': ['https://youtu.be/WcxeMwsBsQA', 'https://youtu.be/ILcpl_WCdJA'],
    'Наши партнёры': ['https://youtu.be/AGn_NHuyK5A', 'https://youtu.be/e6lUbSX8KMM', 'https://youtu.be/lHcHbZS1Si0', 'https://youtu.be/kc9wM__FSBs', 'https://youtu.be/PPyDKb7rjBk'],
    'Наши агенты': ['https://youtu.be/dcoI9vZaCsc'],
    'Обучения': ['https://youtu.be/I_pFZkrcEMs', 'https://youtu.be/p-2lQUbCoWQ', 'https://youtu.be/6lFVsTVrUCk', 'https://youtu.be/iUwTOkdHrVc', 'https://youtu.be/Y7CnD9Yykp8', 'https://youtu.be/K8CTf6BG3Q8', 'https://youtu.be/u6AJZtQ5vT4', 'https://youtu.be/P8uLizE2-nw'],
    'Тренинги': ['https://youtu.be/2Cy_pIjDr3w'],
    'Бизнес-тур (интенсив)': ['https://youtu.be/4nufK2cV9rI', 'https://youtu.be/wu6RCNh9KSA'],
    'Наш сайт': ['https://perspektiva24.com/'],
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
}
url = {
    'Межрегиональные сделки': 'https://t.me/Mejregbot',
    'Аудит вашей компании': 'https://docs.google.com/forms/d/e/1FAIpQLSdo_d0jLnDRgJAWCnFCqiL-ydKK7q49oPG1ZYD9DimnZh_0Yg/viewform?usp=sf_link',
    'Связаться с нами': 'https://t.me/Zarema_Filatova',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
}